### PR TITLE
dhcp6: use new getters

### PR DESCRIPTION
**Pull request by hugelgupf**
pre-req: https://github.com/insomniacslk/dhcp/pull/343

### CODE REVIEW

**Comment by stapelberg** [comment]
Let me know once the dhcp PR is merged and I’ll merge this. Thanks!

**Comment by stapelberg** [comment]
Can you update this for the merged form of the getters please?

**Comment by hugelgupf** [comment]
this is the current form -- it builds for me? 

https://github.com/insomniacslk/dhcp/pull/346 will update the prefix deleg stuff

**Comment by stapelberg** [comment]
Ah, sorry, the build failure is because our travis config was still specifying Go 1.13, I think. Can you rebase onto master please?

**Comment by hugelgupf** [comment]
done ptal thx

**Comment by stapelberg** [comment]
Still fails on travis, this time it looks related:
```
$ go build ./cmd/...
# github.com/rtr7/router7/internal/dhcp6
internal/dhcp6/dhcp6.go:280:33: reply.Options.IAPD undefined (type dhcpv6.Options has no field or method IAPD)
internal/dhcp6/dhcp6.go:293:35: reply.Options.DNS undefined (type dhcpv6.Options has no field or method DNS)
```

**Comment by stapelberg** [comment]
You might need to update go.mod, I suppose?

**Comment by hugelgupf** [comment]
O I c. At the old ref modules weren't on yet.

**Comment by hugelgupf** [comment]
updated. looks to be passing

**Comment by stapelberg** [comment]
Thanks!

**Pull request merged**
