### PR TITLE
dhcp6: use updated DHCPv6 stuff

### PR DESCRIPTION
**Pull request by hugelgupf**
Merge after https://github.com/insomniacslk/dhcp/pull/253

### CODE REVIEW

**Comment by hugelgupf** [comment]
This should be good to merge now.

Sorry I haven't circled back to the dhcp4 issue, been a pretty full plate.

**Comment by hugelgupf** [comment]
@stapelberg please hit that merge button :)

**Comment by stapelberg** [comment]
Let’s see if https://github.com/google/gopacket/pull/622#issuecomment-471909328 can be fixed in the next day or two so that we can do a clean merge with a passing travis run.

Can you remove the empty commit from this PR please? I can re-trigger travis by hitting a button :)

**Comment by hugelgupf** [comment]
Empty commits automatically get removed when you "rebase and merge" on github

**Comment by stapelberg** [comment]
> Empty commits automatically get removed when you "rebase and merge" on github

TIL.

Now merged, thanks!

**Pull request merged**
